### ISSUE TITLE
'Thank you' popup reappears every code start

### ISSUE THREAD

**Issue by iKemp** [SudhanPlayz/NeonDark-Theme#9]
Everytime i start VS-Code the 'Thank you for installing Neon Dark Theme' popup shows up.

![image](https://user-images.githubusercontent.com/22073655/139191413-db8c734d-45cd-4eda-9b10-5b0fae8c3174.png)

**Comment by ItzSudhan** [comment]
> Everytime i start VS-Code the 'Thank you for installing Neon Dark Theme' popup shows up.
> 
> ![image](https://user-images.githubusercontent.com/22073655/139191413-db8c734d-45cd-4eda-9b10-5b0fae8c3174.png)

Sorry about that, I will fix it as soon as possible

**Comment by ItzSudhan** [comment]
#11

**Comment by iKemp** [comment]
Thanks for the quick response.
Unfortunately the update does not work for me.

GET https://open-vsx.org/vscode/gallery/publishers/Sudhan/vsextensions/neondark-theme/1.1.2/vspackage
responds with a whitelabel error page

**Comment by ItzSudhan** [comment]
Its some internal server error sorry i can't do anything about it for now :(
Maybe i will try doing anything to fix this

**Comment by malhabibi** [comment]
I already give a star but still got the "Thank you ..." message, I'm using v1.1.2

**Comment by ItzSudhan** [comment]
> I already give a star but still got the "Thank you ..." message, I'm using v1.1.2

use v1.1.3

**Comment by Tarang** [comment]
I have build v1.2.0 but this still happens consistently.
